#!/bin/bash
# Copyright (C) 2017 EDF SA
# Contact:
#       CCN - HPC <dsp-cspit-ccn-hpc@edf.fr>
#       1, Avenue du General de Gaulle
#       92140 Clamart
#
# Authors: CCN - HPC <dsp-cspit-ccn-hpc@edf.fr>
#
# This file is part of singularity-wrapper.
#
# singularity-wrapper is free software: you can redistribute in and/or
# modify it under the terms of the GNU General Public License,
# version 2, as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with puppet-hpc. If not, see
# <http://www.gnu.org/licenses/>.

set -e

options=()

usage() {
    echo 'usage: ssh [options]' >&2
}

version() {
    ssh_version="$(dpkg-query -W -f '${Version}\n' openssh-client)"
    ssh_version="${ssh_version#*:}"
    ossl_version="$(dpkg-query -W -f '${Version}\n' openssl)"

    printf 'OpenSSH_%s Debian-%s, OpenSSL %s  5 Dec 2014\n' \
	"${ssh_version%-*}" "${ssh_version#*-}" "${ossl_version%-*}" >&2
}

while getopts 1246AaCfgKkMNnqsTtVvXxYyb:c:D:e:F:I:i:L:l:m:O:o:p:R:S:W:w: OPT; do
    case "$OPT" in
        '?')
            usage
            exit 255
            ;;
        V)
            version
            exit
            ;;
	1|2|4|6|A|a|C|f|g|K|k|M|N|n|q|s|T|t|V|v|X|x|Y|y)
            options+=("-$OPT")
	    ;;
        b|c|D|e|F|I|i|L|l|m|O|o|p|R|S|W|w)
            options+=("-$OPT")
            options+=("$OPTARG")
            ;;
    esac
done
shift $(($OPTIND-1))
    
if [ $# -eq 0 ]; then
    usage
    exit 255
fi

host="$1"
shift

if [ $# -eq 0 ]; then
    exec /usr/bin/ssh "${options[@]}" "$host" singularity exec "$SINGULARITY_IMAGE" /bin/bash -l
else
    exec /usr/bin/ssh "${options[@]}" "$host" singularity exec "$SINGULARITY_IMAGE" "$@"
fi

